name: 📬 Spaced Repetition Reminder

on:
  schedule:
    - cron: '30 0 * * *'  # Runs every day at 5:30 AM IST
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install python-dotenv

      - name: Send review reminders
        env:
          EMAIL_USER:     ${{ secrets.EMAIL_USER }}
          EMAIL_APP_PASS: ${{ secrets.EMAIL_APP_PASS }}
          TO_EMAIL:       ${{ secrets.TO_EMAIL }}
        run: |
          python spaced_reminder.py
