name: 🔁 LeetCode Daily Sync

on:
  schedule:
    - cron: '30 0 * * *'   # Daily at 5:30 AM IST
  workflow_dispatch:      # Allows manual trigger

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install leetcode-export python-dotenv requests

      - name: Export LeetCode submissions
        run: |
          leetcode-export \
            --cookies "${{ secrets.LEETCODE_COOKIES }}" \
            --folder auto_sync_bot/submissions \
            --submission-filename "{slug}.{ext}" \
            --only-accepted

      - name: Commit and push submissions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add auto_sync_bot/submissions
          git commit -m "📥 Auto-sync LeetCode submissions" || echo "No changes to commit"
          git push

      - name: Update submissions log
        env:
          LEETCODE_COOKIES:   ${{ secrets.LEETCODE_COOKIES }}
          LEETCODE_USERNAME:  ${{ secrets.LEETCODE_USERNAME }}
        run: |
          python track_submissions.py

      - name: Commit submissions_log.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add submissions_log.json
          git commit -m "🔄 Update submissions_log.json" || echo "No changes"
          git push
