name: LeetCode Daily Sync

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3:00 AM UTC (8:30 AM IST)
  workflow_dispatch:      # Allows manual trigger

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install leetcode-export
        run: pip install leetcode-export

      - name: Export LeetCode submissions
        run: |
          leetcode-export \
            --cookies "${{ secrets.LEETCODE_COOKIES }}" \
            --folder auto_sync_bot/submissions \
            --submission-filename "{slug}.{ext}" \
            --only-accepted

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add auto_sync_bot/submissions
          git commit -m "📥 Auto-sync LeetCode submissions" || echo "No changes to commit"
          git push

      - name: Update submissions log
        run: |
          python track_submissions.py
      - name: Commit log
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add submissions_log.json
          git commit -m "🔄 Update submissions_log.json" || echo "No changes"
          git push